Halium 9.0 to 11.0 Catchup
libhybris/libhybris pull request #529
Opened 2023-01-29 21:10 UTC by fredldotme

This is a continuation of PR #528 with a full rebase on top of libhybris upstream master.
Notable changes include:

- media compat layer enablement for Aethercast (Ubuntu Touch's remote display service)
- camera service enablement on Android 9.0 and up
- general compilation fixes

2023-01-29 21:30 UTC, mlehtima requested changes
I found some style issues when doing a quick check of the changes. Not sure if I found all. I will have more thorough look tomorrow.

2023-01-29 21:30 UTC, mlehtima commented on compat/media/Android.mk
> +    LOCAL_CFLAGS += -std=gnu++0x
Some indentation mismatches in this file here and other places below..

2023-01-29 21:30 UTC, mlehtima commented on compat/surface_flinger/surface_flinger_compatibility_layer.cpp
> +    uint32_t mDisplayLayerStack = 0;
Indentation issues (spaces vs tabs) here and many places below. This file seems to be using tabs.

2023-01-29 21:30 UTC, mlehtima commented on compat/camera/Android.mk
> +    -Wno-unused-parameter \
Indentation should use tabs.

2023-03-30 17:28 UTC, mlehtima commented
@fredldotme do you have any plans to fix the style issues I found or should I fix them after merging?

2023-03-30 17:29 UTC, fredldotme commented
> @fredldotme do you have any plans to fix the style issues I found or should I fix them after merging?

Yes please, I would very much welcome someone helping me. I'm *drowning* in things to patch. :)

2023-04-17 17:15 UTC, merged